name: tugasakhirtpm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  intl: ^0.17.0
  flutter_html: ">=3.0.0-beta.2 <4.0.0"
  image_picker: ^0.8.5+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  

